# Create EIU indicator files

In [2]:
import pandas as pd

In [3]:
eiu_data = pd.read_csv('EIU_Indicators.csv', na_values=['..','--'], encoding="ISO-8859-1")

In [4]:
imf_data = pd.read_csv('IMF_Indicators.csv', na_values=['..','--'], encoding="ISO-8859-1")

In [ ]:
eiu_data.indicator.unique()

Some of our indicators are taken from IMF, hence we need to delete them from here.

In [5]:
def save_excel(out, out2, file_name, indicator_name,source,width=5):
    writer = pd.ExcelWriter(file_name,engine='xlsxwriter')
    out.to_excel(writer,'countries', na_rep='..', index=False, float_format='%.1f', startrow=2)
    out2.to_excel(writer,'aggregates', na_rep='..', index=False, float_format='%.1f', startrow=2)

    workbook  = writer.book
    format1 = workbook.add_format({'bold': True, 'font_size': 14})
    format2 = workbook.add_format({'bold': False, 'font_size': 9, 'italic':True})
    format3 = workbook.add_format({'shrink':True, 'align':'center'})
    format4 = workbook.add_format({'border':1})

    worksheet1 = writer.sheets['countries']
    worksheet1.print_area('A1:AH60') 
    worksheet1.fit_to_pages(1, 1)
    worksheet1.write_string(0, 0, indicator_name, format1)
    worksheet1.write_string(1, 0, source, format2)
    worksheet1.set_column('C:K', None, None, {'hidden': True})
    worksheet1.set_column('B:AH', width, format3)
    worksheet1.set_column('A:A', 13)
    worksheet1.conditional_format('A4:AH60', {'type': 'no_blanks',
                                           'format': format4})
    worksheet1.hide_gridlines(2)
    worksheet1.print_area('A1:AH60') 
    worksheet1.fit_to_pages(1, 1)


    worksheet2 = writer.sheets['aggregates']
    worksheet2.print_area('A1:AH20') 
    worksheet2.write_string(0, 0, indicator_name, format1)
    worksheet2.write_string(1, 0, source, format2)
    worksheet2.set_column('C:K', None, None, {'hidden': True})
    worksheet2.set_column('B:AH', width, format3)
    worksheet2.set_column('A:A', 28)
    worksheet2.conditional_format('A4:AH20', {'type': 'no_blanks',
                                           'format': format4})
    worksheet2.hide_gridlines(2)
    worksheet2.print_area('A1:AH20')
    worksheet2.fit_to_pages(1, 1)
    worksheet2.set_landscape()
    writer.save()

In [6]:
def get_eiu(indicator,df,file_name, source,width):
    cols = ['Economy','1990','1991', '1992', '1993','1994', '1995', '1996', '1997', '1998', 
            '1999', '2000', '2001', '2002', '2003','2004','2005', '2006','2007','2008','2009', '2010',
            '2011','2012','2013', '2014','2015', '2016', '2017', '2018', '2019', '2020', '2021', '2022']
    res1 = pd.DataFrame(columns=cols)
    res2 = pd.DataFrame(columns=cols)
    countries = "Afghanistan, Albania, Algeria, Azerbaijan, Bahrain, Bangladesh, Benin, Brunei, Burkina Faso, Cameroon, Chad, Comoros, Côte d'Ivoire, Djibouti, Egypt, Gabon, Gambia, Guinea, Guinea-Bissau, Guyana, Indonesia, Iran, Iraq, Jordan, Kazakhstan, Kuwait, Kyrgyz Republic, Lebanon, Libya, Malaysia, Maldives, Mali, Mauritania, Morocco, Mozambique, Niger, Nigeria, Oman, Pakistan, Palestine, Qatar, Saudi Arabia, Senegal, Sierra Leone, Somalia, Sudan, Suriname, Syria, Tajikistan, Togo, Tunisia, Turkey, Turkmenistan, U.A.E., Uganda, Uzbekistan, Yemen"
    countries = [x.strip() for x in countries.split(',')]
    regions = ['IDB','IDB Fuel Exporters','IDB Non-Fuel Exporters','IDB SSA Region','IDB SSA Fuel Exporters',
               'IDB SSA Non-Fuel Exporters','IDB ARAB Region','IDB ARAB Fuel Exporters','IDB ARAB Non-Fuel Exporters',
               'IDB ASIA Region','IDB ASIA Fuel Exporters','IDB ASIA Non-Fuel Exporters','IDB LDMC','IDB Non-LDMC',
               'IMF Emerging and Developing Economies','UNCTAD Developed Countries','World']
    i=0
    for country in countries:      
        mask_country = df['economy']== country
        mask_indicator = df['indicator']==indicator
        res1.loc[i] = [country] + df.loc[mask_country & mask_indicator,'1990':'2022'].values[0].tolist()
        i = i+1
    i=0
    rename_region=''
    for region in regions:
        rename_region = region
        if region=='IMF Emerging and Developing Economies':
            rename_region = 'Emerging and Developing Economies'
        if region=='UNCTAD Developed Countries':
            rename_region = 'Advanced Economies'
        mask_country = df['economy']== region
        mask_indicator = df['indicator']==indicator
        res2.loc[i] = [rename_region] + df.loc[mask_country & mask_indicator,'1990':'2022'].values[0].tolist()
        i = i+1
    save_excel(res1,res2,file_name,indicator,source,width)

In [ ]:
get_eiu('Budget balance (% of GDP)', eiu_data, 'bud_balance.xlsx', 'Source: Economist Intelligence Unit (Oct. 2017)')

In [ ]:
get_eiu('Trade balance (% of GDP)', eiu_data, 'trade_balance.xlsx','Source: Economist Intelligence Unit (Oct. 2017)')

In [ ]:
get_eiu('Total debt (% of GDP)', eiu_data, 'total_debt.xlsx','Source: Economist Intelligence Unit (Oct. 2017)')

In [ ]:
get_eiu('International reserves (US$ billion)', eiu_data, 'reserves.xlsx','Source: Economist Intelligence Unit (Oct. 2017)')

In [ ]:
get_eiu('Interest paid (% of GDP)', eiu_data, 'interest.xlsx','Source: Economist Intelligence Unit (Oct. 2017)')

# IMF File

In [ ]:
get_eiu('General Government Revenue (% of GDP)', imf_data, 'gov_revenue.xlsx', 'Source: IMF (Oct. 2017)')

In [ ]:
get_eiu('General Government Total Expenditure (% of GDP)', imf_data, 'gov_expenditure.xlsx', 'Source: IMF (Oct. 2017)')

In [ ]:
get_eiu('Gross National Savings (% of GDP)', imf_data, 'saving.xlsx', 'Source: IMF (Oct. 2017)')

In [ ]:
get_eiu('Total Investment (% of GDP)', imf_data, 'investment.xlsx', 'Source: IMF (Oct. 2017)')

In [ ]:
get_eiu('Current GDP PPP Per Capita (US$)', imf_data, 'GDPPPP.xlsx', 'Source: IMF (Oct. 2017)',width=7)

In [ ]:
get_eiu('General Government Gross Debt (% of GDP)', imf_data, 'gov_debt.xlsx', 'Source: IMF (Oct. 2017)')

# generate html

In [58]:
def delimit(mylist,insert):
    import numpy as np
    sup1 = ''
    sup2 = ''
    mylistnp = np.array(mylist)
    nonnan = np.where(~np.isnan(mylistnp))[0]
    start = nonnan[0]
    last = nonnan[len(nonnan)-1]
    ll = mylist[start:last]
    llnp = np.array(ll)
    llnp = np.around(llnp,decimals=1)
    if start > 0:
        sup1 = 1990 + start
    if last < 32:
        sup2 = 1990 + last
    myarray = ','.join(str(e) for e in llnp.tolist())
    myarray = myarray.replace('nan', 'null')
    myresult =  "<tr><th scope='row'>{}</th><td>{:.1f}<sup>{}</sup></td><td>{:.1f}<sup>{}</sup></td><td><canvas id='BHR' class='sparkline' data-chart_values=[{}]></canvas></td></tr>".format(insert,mylist[start],sup1,mylist[last],sup2,myarray)
    return myresult


In [59]:
def country_html2(df, c_code, c_name):
    import numpy as np
    head = '''
     <h1>{} 
                <a href='indicators/xl/{}.xlsx'>
                  <i class="fa fa-file-excel-o" aria-hidden="true" style="float: right"></i>
                  </a>
                  <a href='indicators/pdf/{}.pdf'>
                  <i class="fa fa-file-pdf-o" aria-hidden="true" style="float: right">&nbsp;&nbsp;&nbsp;</i>
                  </a>
                  </h1>
                <div class="table-responsive">
                  <table class="table table-striped">
               <thead>
                <tr>
                  <th></th>
                  <th>1990</th>
                  <th>2022</th>
                  <th></th>
                </tr>
               </thead>
               <tbody>

    '''.format(c_name,c_code, c_code)
    foot = '''
                </tbody>
              </table>
            </div> 
            <script src="js/line.js"></script>   
        '''
    insert = ''
    for index, row in df.iterrows():
        ll = row[1:].tolist() 
        npll = np.array(ll)
        nonnan = np.where(~np.isnan(npll))[0] # index of non nan
        if nonnan.size == 0: # if the list is full of values for all years
            insert = insert + "<tr><th scope='row'>{}</th><td>..</td><td>..</td><td><canvas id='BHR'></canvas></td></tr>".format(row['Economy'])         
        else:
            insert = insert + delimit(ll,row['Economy'])
    final = head + insert + foot
    Html_file= open("{}.html".format(c_code),"w")
    Html_file.write(final)
    Html_file.close()

In [10]:
file = 'indicators/xl/bud_balance.xlsx'

In [11]:
df1 = pd.read_excel(file, sheetname='countries', header=1, skiprows=1, na_values=['..','--'])

In [12]:
df2 = pd.read_excel(file, sheetname='aggregates', header=1, skiprows=1, na_values=['..','--'])

In [13]:
df = pd.concat([df1,df2])

In [71]:
def prepare_html(filename):
    file = 'indicators/xl/{}.xlsx'.format(filename)
    df1 = pd.read_excel(file, sheetname='countries', header=1, skiprows=1, na_values=['..','--'])
    df2 = pd.read_excel(file, sheetname='aggregates', header=1, skiprows=1, na_values=['..','--'])
    return pd.concat([df1,df2])

In [72]:
country_html2(prepare_html('bud_balance'), 'bud_balance', 'Budget balance (% of GDP)')

In [81]:
country_html2(prepare_html('gov_revenue'), 'gov_revenue', 'General Government Revenue (% of GDP)')

In [80]:
country_html2(prepare_html('gov_expenditure'), 'gov_expenditure', 'General Government Total Expenditure (% of GDP)')

In [79]:
country_html2(prepare_html('saving'), 'saving', 'Gross National Saving (% of GDP)')

In [78]:
country_html2(prepare_html('investment'), 'investment', 'Total Investment (% of GDP)')

In [77]:
country_html2(prepare_html('GDPPPP'), 'GDPPPP', 'Current GDP PPP Per Capita (US$)')

In [76]:
country_html2(prepare_html('trade_balance'), 'trade_balance', 'Trade Balance (% of GDP)')

In [75]:
country_html2(prepare_html('gov_debt'), 'gov_debt', 'General Government Gross Debt (% of GDP)')

In [74]:
country_html2(prepare_html('total_debt'), 'total_debt', 'Total Debt (% of GDP)')

In [73]:
country_html2(prepare_html('reserves'), 'reserves', 'International Reserves (US$ Billion)')

In [82]:
country_html2(prepare_html('interest'), 'interest', 'Interest Paid (% of GDP)')

In [30]:
lll = df.loc[df['Economy']=='Brunei'].values[0].tolist()

In [37]:
lllnp

array([  nan,   nan,   nan, -16.6, -31.2, -31.1, -12. , -16. , -20.3,
         nan,   4. ,  -0.7,  -5.2,   nan,   5.4,  10.8,  20.3,  21.4,
        21.4,  29.7,  -2.3,  14.7,  25.5,  15.9,   7.7,  -1. , -15.1,
       -23. , -16.3,   nan,   nan,   nan,   nan])

In [38]:
nonnan = np.where(~np.isnan(lllnp))[0]

In [39]:
nonnan

array([ 3,  4,  5,  6,  7,  8, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28])

In [41]:
start = nonnan[0]
last = nonnan[len(nonnan)-1]
ll = lllnp[start:last]

In [42]:
ll

array([-16.6, -31.2, -31.1, -12. , -16. , -20.3,   nan,   4. ,  -0.7,
        -5.2,   nan,   5.4,  10.8,  20.3,  21.4,  21.4,  29.7,  -2.3,
        14.7,  25.5,  15.9,   7.7,  -1. , -15.1, -23. ])

In [47]:
np.where(np.isnan(ll), NULL,ll)

NameError: name 'NULL' is not defined

In [49]:
llist=ll.tolist()

In [50]:
teststring = 'data-chart_values=[-5.7,-5.1,-2.5,-1.5,-2.4,0.2,nan,-3.7,3.2,6.1,-0.6,1.3,2.3,1.4,-0.2,3.6,6.3,5.4,4.8,2.8,-0.2,-3.4,-2.4,-4.1,-4.7,-2.8,-6.5,-5.7,-6.6,-5.8,-5.3]>'

In [51]:
teststring

'data-chart_values=[-5.7,-5.1,-2.5,-1.5,-2.4,0.2,nan,-3.7,3.2,6.1,-0.6,1.3,2.3,1.4,-0.2,3.6,6.3,5.4,4.8,2.8,-0.2,-3.4,-2.4,-4.1,-4.7,-2.8,-6.5,-5.7,-6.6,-5.8,-5.3]>'

In [52]:
teststring.replace(',nan,', ',null,')

'data-chart_values=[-5.7,-5.1,-2.5,-1.5,-2.4,0.2,null,-3.7,3.2,6.1,-0.6,1.3,2.3,1.4,-0.2,3.6,6.3,5.4,4.8,2.8,-0.2,-3.4,-2.4,-4.1,-4.7,-2.8,-6.5,-5.7,-6.6,-5.8,-5.3]>'